### ISSUE TITLE
Crashing when using OneDrive

### ISSUE THREAD

**Issue by KeyMeerkat** [agam778/MS-Office-Electron#31]
Hello, I just wanted to say that this is a great app and has been very helpful! However, I have found a potential bug involving OneDrive. When I'm using the OneDrive web interface in this app and go to move my word document to another folder, when I click on the down arrow to the left of a folder in the list, it has a loading symbol and then crashes. I tried doing this 3 times and it kept crashing. I am using the latest version (v0.6.0). Any help would be greatly appreciated.

Thanks!

**Comment by agam778** [comment]
> Hello, I just wanted to say that this is a great app and has been very helpful! However, I have found a potential bug involving OneDrive. When I'm using the OneDrive web interface in this app and go to move my word document to another folder, when I click on the down arrow to the left of a folder in the list, it has a loading symbol and then crashes. I tried doing this 3 times and it kept crashing. I am using the latest version (v0.6.0). Any help would be greatly appreciated.
> 
> Thanks!

Can you send a screen recording or something? It'd be easier to understand and even I'll try the thing you're saying.

**Comment by KeyMeerkat** [comment]
Thanks for getting back so quickly! When I go to Application -> Open logs folder it shows this error:
https://i2.paste.pics/18de8091a20db47046c325d658fe5184.png

And here is a video recording: https://tmpfiles.org/280420/2022-05-0611-56-21.mkv

I hope this helps :)

**Comment by agam778** [comment]
Hi! I tried to reproduce the issue you're facing but it's working fine for me.
I tried both "New windows" and "same window" option, and "Windows" and "Linux" useragent.

About the "Open logs folder" issue, I'll fix it in the future update

**Comment by KeyMeerkat** [comment]
Hi,
Here are my Windows specs:

Edition	Windows 10 Home
Version	21H2
Installed on	‎28/‎05/‎2020
OS build	19044.1682
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by agam778** [comment]
Hmm, I am on Windows 11, didn't occur that issue.
Tried other operations in OneDrive too (for both Normal and Enterprise account), all fine here.

**Comment by KeyMeerkat** [comment]
Ok, maybe it's a windows 10 thing? Do you want my hardware specs?

**Comment by agam778** [comment]
I don't think so that it's a windows 10 thing. And nope, I don't need the hardware specs.
What type of account are you using?

**Comment by KeyMeerkat** [comment]
Hi, sorry I forgot to try your suggestion yesterday. I tried just now with the Linux user agent (I restarted the app like it said), and unfortunately, it still is crashing, I'm not sure what is going wrong.

**Comment by agam778** [comment]
`C:\Users\%USERNAME%\AppData\Roaming\\ms-office-electron\logs\`

Win + R -> Input this and hit enter

And send the `main.log` file please, an error might have been logged there

**Comment by KeyMeerkat** [comment]
Ok, here is [main.log](https://github.com/agam778/MS-Office-Electron/files/8646415/main.log).
For some reason, it doesn't crash on my other user (in Windows). Not sure what is going on. I'll try again on the user that has the problems with the crashing and see if it is fixed.

**Comment by agam778** [comment]
Hmm, the log file doesn't show any errors.

I don't know the issue then, sorry.

**Comment by KeyMeerkat** [comment]
Thanks for your help anyhow, I think there is a problem with one of my Windows users, I will look into the issue more and I'll let you know if I find anything that might be causing this.

**Comment by agam778** [comment]
So, may I close this?

Btw the "Open Logs Folder" issue is already fixed in the latest commit.

**Comment by KeyMeerkat** [comment]
Yes, the issue is partially resolved, you can close it if you want. Thanks for all the help!
